#! /usr/bin/zsh
##
## -*- zsh -*-
##
## zsh_alias for zsh in ~/.myconf/zsh_alias
##
## File for alias

LSOPTS="--tabsize=0 --literal --color=auto --show-control-chars --human-readable -F"
if [ `uname -s` = "NetBSD"  -o  `uname -s` = "FreeBSD" ] && which gls; then
    alias ls="gls $LSOPTS"
elif [ `uname -s` = "Linux" ]; then
    alias ls="ls $LSOPTS"
else
    alias ls="ls -F"
fi

alias l=ls
alias ll="ls -lh"
alias la="ls -A"
alias lla="ls -lah"

alias -- -="cd -"

alias cp="cp -i"
alias mv="mv -i"

alias df="df -h"
alias du="du -h"

alias e="emacs 2> /dev/null"
alias screen="screen -aRAdU"
alias diff='diff -u'
# FIXME: Use egrep, if exist.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias gnus='emacs -f gnus'

# Zlock for use on PIE.
which zlock >/dev/null && alias z="zlock -immed"

if [ "$(uname -s)" != "Linux" ]; then
    alias make='gmake --no-print-directory'
fi

alias m=make
alias man='PAGER=most man'
which svn-wrapper.sh >/dev/null && alias svn='svn-wrapper.sh'

alias ssh-agent='ssh-agent -t 2700'

# alias to some script.
alias ns='~/script/ns_who.sh'
alias sn=ns

# global alias
alias -g L='|less'
alias -g G='|egrep'
