-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1280,
                    ["h"] = 1024,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1280,
                            ["h"] = 1024,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1009,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1278,
                                                ["h"] = 990,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 8388621,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 6,
                                                        ["x"] = 3,
                                                        ["w"] = 1273,
                                                        ["h"] = 979,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["geom"] = {
                                                ["y"] = 18,
                                                ["x"] = 1,
                                                ["w"] = 1278,
                                                ["h"] = 990,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 10485767,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1278,
                                                        ["h"] = 990,
                                                    },
                                                    ["level"] = 0,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 272,
                            ["x"] = 320,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1024,
                        ["mode"] = 0,
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<2>",
                                ["geom"] = {
                                    ["y"] = 18,
                                    ["x"] = 1,
                                    ["w"] = 638,
                                    ["h"] = 460,
                                },
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 12582936,
                                        ["checkcode"] = 3,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 638,
                                            ["h"] = 460,
                                        },
                                        ["level"] = 0,
                                    },
                                },
                                ["level"] = 0,
                            },
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1280,
                    ["h"] = 1024,
                },
                ["hidden"] = true,
            },
        },
    },
}

