#!/bin/sh
#
# This is an example of using HGEDITOR to create of diff to review the
# changes while commiting.

# If you want to pass your favourite editor some other parameters
# only for Mercurial, modify this:
case "${EDITOR}" in
    "")
        EDITOR="vi"
        ;;
    emacs)
        EDITOR="$EDITOR -nw"
        ;;
    gvim|vim)
        EDITOR="$EDITOR -f -o"
        ;;
esac

HGTMP=""
cleanup_exit() {
    rm -rf "$HGTMP"
}

# Remove temporary files even if we get interrupted
trap "cleanup_exit" 0 # normal exit
trap "exit 255" 1 2 3 6 15 # HUP INT QUIT ABRT TERM

for i in gsed gnused sed
do
  if $i --version > /dev/null 2>&1; then
    sed=$i
    break
  fi
done

if test x"$sed" = x; then
  echo >&2 "$0: GNU Sed is required and was not found"
  exit 52
fi

if $sed '/^diff --git/{g;q;}' "$file" |
    grep -v '^#' |
    grep -v '^$' |
    grep -v '^Signed-off-by:'; then
    # The commit message is already filled (commit --amend, for instance)
    exit 0
fi

format ()
{
    $sed '
/^?/Q
# Pretty print transformations
s/^M \(.*\)$/\t* \1: ./
s/^A \(.*\)$/\t* \1: New./
s/^R \(.*\)$/\t* \1: Remove./
/^!/ d
'
}

HGTMP="${TMPDIR-/tmp}/hgeditor.$RANDOM.$RANDOM.$RANDOM.$$"
(umask 077 && mkdir "$HGTMP") || {
    echo "Could not create temporary directory! Exiting." 1>&2
    exit 1
}

(
    grep '^HG: changed' "$1" | cut -b 13- | while read changed; do
        "$HG" diff "$changed" >> "$HGTMP/diff"
    done
)


echo . > "$HGTMP/msg"
echo >> "$HGTMP/msg"
"$HG" status | format | sort >> "$HGTMP/msg"
cat "$1" | $sed '1d' >> "$HGTMP/msg"

MD5=$(which md5sum 2>/dev/null) || \
    MD5=$(which md5 2>/dev/null)
[ -x "${MD5}" ] && CHECKSUM=`${MD5} "$HGTMP/msg"`
if [ -s "$HGTMP/diff" ]; then
    # Use vim instand of default editor
    vim "+e $HGTMP/diff" '+set buftype=help filetype=diff' "+vsplit $HGTMP/msg" || exit $?
    # $EDITOR "$HGTMP/diff" "$HGTMP/msg" || exit $?
else
    $EDITOR "$HGTMP/msg" || exit $?
fi
[ -x "${MD5}" ] && (echo "$CHECKSUM" | ${MD5} -c >/dev/null 2>&1 && exit 13)

mv "$HGTMP/msg" "$1"

exit $?
