#! /usr/bin/zsh
##
## -*- zsh -*-
##
## zsh_alias for zsh in ~/.myconf/zsh_alias
##
## File for alias

LSOPTS="--tabsize=0 --literal --color=auto --show-control-chars --human-readable -F"
if [ `uname -s` = "NetBSD"  -o  `uname -s` = "FreeBSD" ] && which gls; then
    alias ls="gls $LSOPTS"
elif [ `uname -s` = "Linux" ]; then
    alias ls="ls $LSOPTS"
else
    alias ls="ls -F"
fi

alias l=ls
alias ll="ls -lh"
alias la="ls -A"
alias lla="ls -lah"

alias -- -="cd -"

alias cp="cp -i"
alias mv="mv -i"

alias crontab='crontab -i'

alias df="df -h"
alias du="du -h"

alias bc='bc -l'

alias screen="screen -aRAdU"
alias diff='diff -u'
# FIXME: Use egrep, if exist.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias gnus='emacs -f gnus'

alias touchold='touch -t 01010000'
alias today='date +%Y-%m-%d'

if [ "$(uname -s)" != "Linux" ]; then
    alias make='gmake --no-print-directory'
else
    alias make='make --no-print-directory'
fi

alias m="ionice nice make -j$(([#10] $(egrep -c '^processor' /proc/cpuinfo) * 1.5))"
# TODO try to have color and a less like beahvior (maybe vim like)
#alias man='PAGER=most man'
which svn-wrapper.sh >/dev/null && alias svn='svn-wrapper.sh'

alias ssh-agent='ssh-agent -t 2700'

myagent() {
    ~/.myconf/script/ssh-agent.sh $@
    source ~/.ssh/ssh-agent.$(hostname)
}

todo() {
  sh -c "cd; ~/.myconf/script/todo.sh $@"
}

mkcd() {
  mkdir "$@"
  cd "$1"
}

# global alias
alias -g L='|less -r'
alias -g La='2>&1|less -r'
alias -g G='|egrep'
alias -g T='|tail'
alias -g H='|head'
